---
# install haveged
# replace crypto task

- name: Add the OS specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: install haveged
  package:
    name: "{{ haveged_pkg }}"
    state: latest

- name: enable haveged
  service:
    name: "{{ haveged_service}}"
    state: started
    enabled: yes

