---

- name: Hardening postfix 
  command: postconf -e '{{ item }}'
  with_items:
  - 'smtpd_banner = $myhostname ESMTP Intercloud'
  - 'disable_vrfy_command = yes'
  - 'inet_interfaces = loopback-only'
  - 'smtp_tls_loglevel=1'
  - 'smtpd_tls_loglevel=1'
  - 'smtp_use_tls = yes'
  - 'smtpd_use_tls = yes'
  - 'smtp_tls_mandatory_protocols = !SSLv2, !SSLv3, !TLSv1, !TLSv1.1'
  - 'smtp_tls_protocols = !SSLv2, !SSLv3, !TLSv1, , !TLSv1.1'
  - 'smtpd_tls_mandatory_protocols = !SSLv2, !SSLv3, !TLSv1, !TLSv1.1'
  - 'smtpd_tls_protocols = !SSLv2, !SSLv3, !TLSv1, !TLSv1.1'
  - 'smtp_tls_exclude_ciphers = EXP, MEDIUM, LOW, DES, 3DES, SSLv2'
  - 'smtpd_tls_exclude_ciphers = EXP, MEDIUM, LOW, DES, 3DES, SSLv2'
  - 'tls_high_cipherlist = kEECDH:+kEECDH+SHA:kEDH:+kEDH+SHA:+kEDH+CAMELLIA:kECDH:+kECDH+SHA:kRSA:+kRSA+SHA:+kRSA+CAMELLIA:!aNULL:!eNULL:!SSLv2:!RC4:!MD5:!DES:!EXP:!SEED:!IDEA:!3DES:!SHA'
  - 'smtp_tls_ciphers = high'
  - 'smtpd_tls_ciphers = high' 
  - 'smtpd_tls_security_level = may'
