---
# Enforce sysctl hardening
- name: Enforce sysctl hardening
  sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
  with_dict: "{{ kernel_parameters }}"

- name: Enforce sysctl hardening || RedHat based distro tuning
  sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
  with_dict: "{{ redhat_kernel_parameters }}"
  when: ansible_os_family  == "CentOS" or ansible_os_family == "RedHat"

- name: Enforce sysctl hardening 
  sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
  with_dict: "{{ ufw_kernel_parameters }}"
  when: ansible_os_family == "Ubuntu"

- name: Handle ufw (firewall) sysctl config (Ubuntu)
  lineinfile:
    dest: /etc/ufw/sysctl.conf
    regexp: '^({{ item.key }})=[0-9]+'
    line: '{{ item.key }}={{ item.value }}'
    state: present
  with_items:
  - { key: 'net/ipv4/conf/all/log_martians', value: '1' }
  - { key: 'net/ipv4/conf/all/accept_redirects', value: '0' }
  - { key: 'net/ipv4/tcp_syncookies', value: '1' }
  when: ansible_os_family == "Ubuntu"
